spring:
  application:
    name: oauth2-resource-server
server:
  port: 8090
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:90000
#          jwk-set-uri: http://localhost:9000/oauth2/jwks